name: "Terraform apply staging"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "terragrunt/**"
      - "!terragrunt/env/production/**"
      - ".github/workflows/tf_apply_staging.yml"

env:
  AWS_REGION: ca-central-1
  TERRAFORM_VERSION: 1.11.2
  TERRAGRUNT_VERSION: 0.75.6
  TF_VAR_jwt_secret_key: ${{ secrets.JWT_SECRET_KEY }}
  TF_VAR_sentinel_customer_id: ${{ secrets.LOG_ANALYTICS_WORKSPACE_ID }}
  TF_VAR_sentinel_shared_key: ${{ secrets.LOG_ANALYTICS_WORKSPACE_KEY }}

permissions:
  id-token: write
  contents: read
  pull-requests: write
  actions: write
  checks: write
  statuses: write

jobs:
  terragrunt-apply:
    if: github.repository == 'cds-snc/dto-feedback-viewer'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform Tools
        uses: cds-snc/terraform-tools-setup@v1

      - name: Configure aws credentials using OIDC
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
        with:
          role-to-assume: arn:aws:iam::992382783569:role/dto-feedback-viewer-apply
          role-session-name: TFApply
          aws-region: ${{ env.AWS_REGION }}

      - name: Apply ssm
        working-directory: terragrunt/env/staging/ssm
        run: terragrunt apply --terragrunt-non-interactive -auto-approve

      - name: Apply hosted zone
        working-directory: terragrunt/env/staging/hosted_zone
        run: terragrunt apply --terragrunt-non-interactive -auto-approve

      - name: Apply ecr
        working-directory: terragrunt/env/staging/ecr
        run: terragrunt apply --terragrunt-non-interactive -auto-approve

      - name: Apply iam
        working-directory: terragrunt/env/staging/iam
        run: terragrunt apply --terragrunt-non-interactive -auto-approve

      - name: Apply load balancer
        working-directory: terragrunt/env/staging/load_balancer
        run: terragrunt apply --terragrunt-non-interactive -auto-approve

      - name: Apply ecs
        working-directory: terragrunt/env/staging/ecs
        run: terragrunt apply --terragrunt-non-interactive -auto-approve
